### ISSUE TITLE
No suitable disks have been found | KVM | Guest

### ISSUE THREAD

**Issue by taumeister** [64kramsystem/zfs-installer#247]
I face the same problem on all supported versions:

No suitable disks have been found! 
I youre running inside a VMWare virtual machine...

but I use KVM, and never had to enable disk.EnableUUID, this is something I know from VMWare machines.

[disks.log](https://github.com/64kramsystem/zfs-installer/files/7537578/disks.log)

**Comment by 64kramsystem** [comment]
Hello!

I'll check it over this week. The log helps considerably :smile:

**Comment by taumeister** [comment]
*update*
The cause is the paravirtualized disk [virtio], it has to be a 'sata' disk.
Did not know, that a virtio disk does not show uuids...hmm.

**Comment by 64kramsystem** [comment]
> _update_ The cause is the paravirtualized disk [virtio], it has to be a 'sata' disk. Did not know, that a virtio disk does not show uuids...hmm.

thanks for the update. ok, I'll close the issue, then :slightly_smiling_face:
